import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from '@/components/providers'
import { RouterMounting } from '@/components/routermounting'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'vtecx next blank',
  description: 'Generated by ReflexWorks'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body>
        <Providers>
          <RouterMounting>{children}</RouterMounting>
        </Providers>
      </body>
    </html>
  )
}
